Bump prettier from 3.6.0 to 3.6.1 in the javascript group (#57)
Bumps the javascript group with 1 update:
[prettier](https://github.com/prettier/prettier).

Updates `prettier` from 3.6.0 to 3.6.1
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/prettier/prettier/releases">prettier's
releases</a>.</em></p>
<blockquote>
<h2>3.6.1</h2>
<ul>
<li>Fix &quot;Warning: File descriptor 39 closed but not opened in
unmanaged mode&quot; error when running
<code>--experimental-cli</code></li>
</ul>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#361">Changelog</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md">prettier's
changelog</a>.</em></p>
<blockquote>
<h1>3.6.1</h1>
<p><a
href="https://github.com/prettier/prettier/compare/3.6.0...3.6.1">diff</a></p>
<h4>TypeScript: Allow const without initializer (<a
href="https://redirect.github.com/prettier/prettier/pull/17650">#17650</a>,
<a
href="https://redirect.github.com/prettier/prettier/pull/17654">#17654</a>
by <a href="https://github.com/fisker"><code>@​fisker</code></a>)</h4>
<!-- raw HTML omitted -->
<pre lang="jsx"><code>// Input
export const version: string;
<p>// Prettier 3.6.0 (--parser=babel-ts)<br />
SyntaxError: Unexpected token (1:21)<br />
&gt; 1 | export const version: string;<br />
|                     ^</p>
<p>// Prettier 3.6.0 (--parser=oxc-ts)<br />
SyntaxError: Missing initializer in const declaration (1:14)<br />
&gt; 1 | export const version: string;<br />
|              ^^^^^^^^^^^^^^^</p>
<p>// Prettier 3.6.1<br />
export const version: string;<br />
</code></pre></p>
<h4>Miscellaneous: Avoid closing files multiple times (<a
href="https://redirect.github.com/prettier/prettier/pull/17665">#17665</a>
by <a href="https://github.com/43081j"><code>@​43081j</code></a>)</h4>
<p>When reading a file to infer the interpreter from a shebang, we use
the
<code>n-readlines</code> library to read the first line in order to get
the shebang.</p>
<p>This library closes files when it reaches EOF, and we later try close
the same
files again. We now close files only if <code>n-readlines</code> did not
already close
them.</p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/prettier/prettier/commit/2bfff20275b8de52b9bdd987f966ff8ac198b71b"><code>2bfff20</code></a>
Release 3.6.1</li>
<li><a
href="https://github.com/prettier/prettier/commit/cb8af6c59b897835687917c2719104ef182ea1b0"><code>cb8af6c</code></a>
Disable &quot;Linting files&quot; step on release</li>
<li><a
href="https://github.com/prettier/prettier/commit/65e603d414d06b8eee36479014cfc5825bb32e88"><code>65e603d</code></a>
chore(deps): update dependency jest to v30.0.3 (<a
href="https://redirect.github.com/prettier/prettier/issues/17667">#17667</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/37f6e09589c44b455571a1f1876cec364b5e0fab"><code>37f6e09</code></a>
Avoid closing files multiple times in <code>getInterpreter</code>(<a
href="https://redirect.github.com/prettier/prettier/issues/17665">#17665</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/0e6ec982df2b8c7653a6a2d2dd35107a70d5a1b6"><code>0e6ec98</code></a>
chore(deps): update dependency meriyah to v6.1.3 (<a
href="https://redirect.github.com/prettier/prettier/issues/17666">#17666</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/4292cbf2ef9db4a272e0747bd90ad567b6b8b05a"><code>4292cbf</code></a>
Disable <code>experimentalRawTransfer</code> for oxc parser (<a
href="https://redirect.github.com/prettier/prettier/issues/17663">#17663</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/e9045d0fcc087da5662042ac5da01a8da25ee15a"><code>e9045d0</code></a>
Docs: delete outdated part about decorators (<a
href="https://redirect.github.com/prettier/prettier/issues/17662">#17662</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/0926587a5fc4134b5773e54a2739cc5576c4dd23"><code>0926587</code></a>
Allow const without initializer in <code>oxc-ts</code> parser (<a
href="https://redirect.github.com/prettier/prettier/issues/17654">#17654</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/456179ace8c0ebe321821f72019a4c011d532310"><code>456179a</code></a>
Fix typo in v3.6.0 release notes for markdown (<a
href="https://redirect.github.com/prettier/prettier/issues/17661">#17661</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/75bdb5d5de50308c396657dcbda70b60798f5d09"><code>75bdb5d</code></a>
Add issue link for the experimental CLI (<a
href="https://redirect.github.com/prettier/prettier/issues/17659">#17659</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/prettier/prettier/compare/3.6.0...3.6.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=prettier&package-manager=npm_and_yarn&previous-version=3.6.0&new-version=3.6.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>